INSERT INTO TEMPLATE.TAB_PESSOA (ID_PESSOA, NOME, IDADE, DATA_CRIACAO, DATA_ATUALIZACAO) VALUES (1, 'Nome de Pessoa #1', 11, CURRENT_TIMESTAMP, NULL);
INSERT INTO TEMPLATE.TAB_PESSOA (ID_PESSOA, NOME, IDADE, DATA_CRIACAO, DATA_ATUALIZACAO) VALUES (2, 'Nome de Pessoa #2', 22, CURRENT_TIMESTAMP, NULL);
INSERT INTO TEMPLATE.TAB_PESSOA (ID_PESSOA, NOME, IDADE, DATA_CRIACAO, DATA_ATUALIZACAO) VALUES (3, 'Nome de Pessoa #3', 33, CURRENT_TIMESTAMP, NULL);
INSERT INTO TEMPLATE.TAB_PESSOA (ID_PESSOA, NOME, IDADE, DATA_CRIACAO, DATA_ATUALIZACAO) VALUES (4, 'Nome de Pessoa #4', 44, CURRENT_TIMESTAMP, NULL);
INSERT INTO TEMPLATE.TAB_PESSOA (ID_PESSOA, NOME, IDADE, DATA_CRIACAO, DATA_ATUALIZACAO) VALUES (5, 'Nome de Pessoa #5', 55, CURRENT_TIMESTAMP, NULL);
INSERT INTO TEMPLATE.TAB_PESSOA (ID_PESSOA, NOME, IDADE, DATA_CRIACAO, DATA_ATUALIZACAO) VALUES (6, 'Nome de Pessoa #6', 66, CURRENT_TIMESTAMP, NULL);
INSERT INTO TEMPLATE.TAB_PESSOA (ID_PESSOA, NOME, IDADE, DATA_CRIACAO, DATA_ATUALIZACAO) VALUES (7, 'Nome de Pessoa #7', 77, CURRENT_TIMESTAMP, NULL);