GRANT DELETE ON TEMPLATE.TAB_PESSOA TO USR_TEMPLATE;
GRANT INSERT ON TEMPLATE.TAB_PESSOA TO USR_TEMPLATE;
GRANT SELECT ON TEMPLATE.SEQ_TAB_PESSOA TO USR_TEMPLATE;
GRANT SELECT ON TEMPLATE.TAB_PESSOA TO USR_TEMPLATE;
GRANT UPDATE ON TEMPLATE.TAB_PESSOA TO USR_TEMPLATE;